---
name: Test docker

on:
  schedule:
    - cron: "0 6,18 * * *"
  push:
    paths:
      - "docker/Dockerfile"
  pull_request:
    paths:
      - "docker/Dockerfile"


jobs:
  build_image:
    name: "Build standard image"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
        docker build -f docker/Dockerfile-bionic . -t nle:bionic-$SHORT_SHA

  build_image:
    name: "Build xenial image"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: |
        SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
        docker build -f docker/Dockerfile-xenial . -t nle:xenial-$SHORT_SHA

...
